client-reputation-service:
  url: http://127.0.0.1:8081

delivery-cost-service:
  url: http://127.0.0.1:8081

special-price-catalogue-service:
  url: http://127.0.0.1:8081

spring:
  jackson:
    visibility:
      field: any
  web:
    locale: en

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG